databases:
  - name: demosi61-db
    databaseName: datos1
    user: demosi61_user
    plan: free

services:
  - type: web
    name: demosi61-api
    runtime: java
    plan: free
    branch: main
    buildCommand: ./mvnw clean install -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=production -jar target/demoSI61-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: demosi61-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
