databases:
  - name: demosi61-db
    databaseName: datos1
    user: demosi61_user
    plan: free

services:
  - type: web
    name: demosi61-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: demosi61-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
